### ISSUE TITLE
Usage in .NetStandard2.0 library can cause MethodNotFound exception

### ISSUE THREAD

**Issue by mgoodfellow** [Turnerj/Quickenshtein#45]
Hi,

If you include this package into a .NetStandard2.0 library, and invoke the method signatures of

` Levenshtein.GetDistance(string, string)` or ` Levenshtein.GetDistance(string, string, CalculationOptions)`

Then call this from a test project (for example), where the project is .net5 / .netcore etc, then when invoking the method, you will get a `MissingMethodException`

This happens because [the methods are only present in netstandard](https://github.com/Turnerj/Quickenshtein/blob/main/src/Quickenshtein/Levenshtein.cs#L16) 

This can be fixed by using string extensions `.AsSpan()` to cause the [other form included in all outputs](https://github.com/Turnerj/Quickenshtein/blob/main/src/Quickenshtein/Levenshtein.cs#L49) to be used instead.

Unless I'm missing something, why are these methods only included if this is a .netstandard library?

**Comment by Turnerj** [comment]
Oh, that's interesting - never realised that! I think my original intention with the string variant was to add some minor optimizations for .NET Framework which seemed irrelevant for .NET Core with `ReadOnlySpan<char>` etc. Its definitely a good idea to re-evaluate whether that is truly useful and whether I don't just do as you've suggested and call the overload.

**Comment by Turnerj** [comment]
Again, great catch for finding this issue, raising it and submitting a PR - I really appreciate it! Will release a new version with this change now!

**Comment by winstxnhdw** [comment]
Hey @Turnerj, same thing here is happening but for `netstandard2.1`. In my case, I am calling `public unsafe static int GetDistance(ReadOnlySpan<char> source, ReadOnlySpan<char> target, CalculationOptions calculationOptions)` directly. There's no issue if I call `Levenshtein.GetDistance(string, string)` instead.
