### ISSUE TITLE
On .NET framework 4.8 this library is slower than super simple 1 file equivalent. Is that normal?

### ISSUE THREAD

**Issue by zyo2012** [Turnerj/Quickenshtein#86]
Hi, I've been running a benchmark and found that it's slower than single file <100 lines Fastenshtein algo
- Is that because I'm NOT on the .NET CORE framework?
- You algo, doesn't allocate memory, that's awesome, but still slower !¿?
- My test compare rather small strings < 20 characters.

Other implementation
https://github.com/DanHarltey/Fastenshtein/blob/master/src/Fastenshtein/Levenshtein.cs

BenchmarkDotNet=v0.13.2, OS=Windows 10 (10.0.19043.2130/21H1/May2021Update)
AMD Ryzen 9 5900X, 1 CPU, 24 logical and 12 physical cores
  [Host]     : .NET Framework 4.8 (4.8.4515.0), X86 LegacyJIT
  DefaultJob : .NET Framework 4.8 (4.8.4515.0), X86 LegacyJIT

|                 Method |   N |     Mean |   Error |  StdDev |   Gen0 | Allocated |
|----------------------- |---- |---------:|--------:|--------:|-------:|----------:|
|           Fastenshtein | 100 | 598.5 ns | 1.67 ns | 1.40 ns | 0.3443 |     573 B |
|          Quickenshtein | 100 | 901.5 ns | 1.26 ns | 1.05 ns |      - |         - |

**Comment by Turnerj** [comment]
Quickenshtein works best with .NET Core 3.1 and newer but can still perform well with .NET Framework though in any case, it will depend on the strings being used.

Some of the best optimizations really kick into gear with long strings, others help with strings that share a common start/end.

In a case with short strings on .NET Framework with nothing to trim, it is probably in its worst position. There is probably some additional tuning I can do to make the lower end better but at the point where 10 character comparison is maybe 310 branches of code in the simplest form, it is hard to simultaneously scale that low in processing to scaling over 100,000 characters. A branching change that helps huge strings is an extra branch a short string will need to process. When talking nanosecond scale, every branch counts.

These are the benchmark result numbers that I publish: https://github.com/Turnerj/Quickenshtein/blob/main/docs/OverallComparison.md

You can see that short strings trade blows with Fastenshtein though certain combos are worse than others. Once it is with longer strings, Quickenshtein gets to stretch its legs.

I don't have a 5900X for an apples-to-apples comparison but I am curious what the strings were in the benchmark you've cited. Again, I might be able to tune shorter strings but I can't really make more branching logic run faster than less.

**Comment by Turnerj** [comment]
Oh, I should mention is that my benchmarks are running with X64 RyuJIT rather than X86 LegacyJIT for both .NET Core and .NET Framework which, while likely improving both Quickenshtein and Fastenshtein, would also change the benchmarked result.

Read more about RyuJIT here: https://devblogs.microsoft.com/dotnet/ryujit-the-next-generation-jit-compiler-for-net/

**Comment by Turnerj** [comment]
Here is an example of what I mean by depending on the strings being used etc. This is an example I threw together in LINQPad and uses .NET 6 however the general concept is the same.

One attempt is with these "similar" strings:
- `Hello World, 123 ABC`
- `Hello world! 123 DEF`

Another attempt is with these strings:
- `Hello World, 123 ABC`
- `This is not similar!`

In the first attempt, Quickenshtein is faster, in the second Fastenshtein is faster. The reason for it in this case is that Quickenshtein can do trimming on similar strings - the bigger the similarity at the start and end, the more Quickenshtein can improve performance. When they don't, Quickenshtein is doing extra processing to check if that is the case while Fastenshtein is already starting the calculation.

```
BenchmarkDotNet=v0.13.2, OS=Windows 10 (10.0.19044.2006/21H2/November2021Update)
Intel Core i7-6700HQ CPU 2.60GHz (Skylake), 1 CPU, 8 logical and 4 physical cores
.NET SDK=6.0.400
  [Host] : .NET 6.0.8 (6.0.822.36306), X64 RyuJIT AVX2

Job=.NET 6.0  Runtime=.NET 6.0  
```

|            Method | SimilarStrings |     Mean |   Error |  StdDev |   Gen0 | Allocated |
|------------------ |--------------- |---------:|--------:|--------:|-------:|----------:|
|  WithFastenshtein |          False | 663.8 ns | 6.58 ns | 5.83 ns | 0.0324 |     104 B |
| WithQuickenshtein |          False | 935.7 ns | 6.79 ns | 6.35 ns |      - |         - |
|  WithFastenshtein |           True | 672.1 ns | 6.83 ns | 6.39 ns | 0.0324 |     104 B |
| WithQuickenshtein |           True | 516.4 ns | 4.63 ns | 4.33 ns |      - |         - |

```csharp
[MemoryDiagnoser]
[SimpleJob(RuntimeMoniker.Net60)]
public class TestBenchmark
{
	[Params(false, true)]
	public bool SimilarStrings;
	
	public string StringA { get; set; }
	public string StringB { get; set; }
	
	[GlobalSetup]
	public void Setup()
	{
		if (SimilarStrings)
		{
			StringA = "Hello World, 123 ABC";
			StringB = "Hello world! 123 DEF";
		}
		else
		{
			StringA = "Hello World, 123 ABC";
			StringB = "This is not similar!";
		}
	}

	[Benchmark]
	public int WithFastenshtein()
	{
		return Fastenshtein.Levenshtein.Distance(StringA, StringB);
	}

	[Benchmark]
	public int WithQuickenshtein()
	{
		return Quickenshtein.Levenshtein.GetDistance(StringA, StringB);
	}
}
```
